AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  my-sam-function

  Sample SAM Template for my-sam-function
  
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  CustomerDetailFunction:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      Events:
        CustomerDetail:
          Type: Api
          Properties:
            Path: /getCustomerDetail
            Method: get
    Metadata:
      DockerTag: nodejs12.x-v1
      DockerContext: ./hello-world
      Dockerfile: Dockerfile

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  CustomerDetailApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/getCustomerDetail/"
  CustomerDetailFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt CustomerDetailFunction.Arn
  CustomerDetailFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt CustomerDetailFunctionRole.Arn
